### ISSUE TITLE
bash in `debian/eol:wheezy` results in segmentation fault but `/bin/sh` works

### ISSUE THREAD

**Issue by flybyray** [debuerreotype/docker-debian-eol-artifacts#5]
I am not quite sure if this is known or somewhere workarrounds exist:

Currently the image would crash with 139  segfault.

It is only possible to run with `/bin/sh` as entrypoint:

`docker run -it --rm --entrypoint /bin/sh debian/eol:wheezy`

**Comment by flybyray** [comment]
just to old: https://github.com/docker/for-win/issues/6509

why those images are still available then?

what are the requirements to run them?

**Comment by tianon** [comment]
You probably need to add `vsyscall=emulate` to your kernel command-line flags if you want/need to run Wheezy or older containers; see also https://github.com/moby/moby/issues/28705.

I maintain these mostly for the purposes of software preservation, not because folks should be running them for production workloads (as their EOL status typically makes them ripe with security issues).

**Comment by flybyray** [comment]
Thank you for that hint. I will try that.
I just tried to figure out some software dependencies for a UniFi usg-3p which uses a vyatta on Debian 7. Hence I used it exactly as you mentioned the use case.
